# Generated by Django 3.2 on 2022-02-06 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('12:00', '12pm'), ('14:00', '2pm'), ('16:00', '4pm'), ('18:00', '6pm'), ('20:00', '8pm'), ('22:00', '10pm')], default='12pm', max_length=10)),
                ('event', models.CharField(choices=[('private_function', 'Private Function'), ('large_group_booking', 'Large Group Booking'), ('feedback_comment', 'Feedback or Comment'), ('other', 'Other')], max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
