# Generated by Django 3.2 on 2022-02-03 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservations',
            options={'ordering': ['date']},
        ),
    ]
