# Generated by Django 3.2 on 2022-02-03 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservations_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservations',
            options={'ordering': ['date'], 'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
    ]
