# Generated by Django 3.2 on 2022-02-04 21:48

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservations_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
