# Generated by Django 3.2 on 2022-02-06 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservations_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='number_of_party',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, 5), (6, 6)], default=1),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='phone_number',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='time',
            field=models.CharField(choices=[('12:00', '12pm'), ('14:00', '2pm'), ('16:00', '4pm'), ('18:00', '6pm'), ('20:00', '8pm'), ('22:00', '10pm')], default='12pm', max_length=10),
        ),
    ]
