# Generated by Django 3.2 on 2022-02-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_alter_reservations_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='reservation_id',
        ),
        migrations.AddField(
            model_name='reservations',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
