# Generated by Django 3.2 on 2022-02-08 22:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_auto_20220208_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='id',
        ),
        migrations.AddField(
            model_name='reservations',
            name='reservation_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
