# Generated by Django 3.2 on 2022-02-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_auto_20220208_2331'),
    ]

