# Generated by Django 3.2 on 2022-02-08 23:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_alter_reservations_id'),
    ]
