# Generated by Django 3.2 on 2022-02-08 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0016_auto_20220208_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='id',
        ),
        migrations.AddField(
            model_name='reservations',
            name='reservation_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
