# Generated by Django 3.2 on 2022-02-09 04:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_auto_20220208_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='phone_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
