# Generated by Django 3.2 on 2022-02-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_one', models.ImageField(upload_to='images/menu_page-0001.jpg')),
                ('img_two', models.ImageField(upload_to='images/')),
                ('img_three', models.ImageField(upload_to='images/')),
                ('img_four', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
