# Generated by Django 3.2 on 2022-02-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='img_four',
            field=models.ImageField(upload_to='', verbose_name='/images/menu_page-0001.jpg'),
        ),
    ]
